### ISSUE TITLE
Why not Swift?

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/CardStack#1]
Why is this not written in Swift?

**Comment by 3lvis** [comment]
Yes!

:+1: for Swift!

**Comment by attila-at-hyper** [comment]
I know nothing about Swift yet. Yes, I know, shame on me, but as we’re on a tight (er, behind) schedule, I thought it isn’t the appropriate time to start learning. but I will do port it to Swift as soon as time pressure is down a bit.

**Comment by 3lvis** [comment]
We're trying to not rewrite working code into Swift, would be great if it's something you consider on your next Pod :)

Also don't feel afraid of just pinging for help/feedback some people in the team have Swift experience and might help you to get up and running. \o/
