### ISSUE TITLE
UICollectionView

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/CardStack#2]
I played with this before doing collections. Maybe it could have been useful for inspiration.

https://github.com/3lvis/ANDYCardStack

**Comment by attila-at-hyper** [comment]
I have seen it once before, but to be honest I've forgotten. Sorry about that. This reminds me an issue I wanted to raise earlier: we have a great team, creating a lot of stuff we could potentially use, reuse and/or build upon in ongoing projects. But how the heck can we know all the stuff created and remain up-to-date?

**Comment by 3lvis** [comment]
Most of the team members are very active on Slack, maybe a message there could help :)

Anyway, sorry for the inconvenience.
