### ISSUE TITLE
Restoring consistency in viewController tags should be handled by the library

### ISSUE THREAD

**Issue by 3lvis** [hyperoslo/CardStack#23]
The processing in the completion block should be necessary. Data consistency should be handled by the library.

``` objc
- (void)removeAction:(UIButton *)button {
    NSInteger index = button.superview.tag;
    [self.cardStackController removeCardAtIndex:index animated:YES withCompletion:^{
        for (NSUInteger i = 0; i < self.viewControllers.count; i++) {
            UIViewController *viewController = [self.viewControllers objectAtIndex:i];
            viewController.view.tag = i;
        }
    }];
}
```

This should just work:

``` objc
- (void)removeAction:(UIButton *)button {
    NSInteger index = button.superview.tag;
    [self.cardStackController removeCardAtIndex:index animated:YES withCompletion:nil];
}
```

**Comment by attila-at-hyper** [comment]
@3lvis: tagging view controllers (unlike tagging cards) wasn't planned to be a generic thing. It's used only by the example app. That's why it wasn't added to the library (but can be changed if you think it's a generic request).

**Comment by 3lvis** [comment]
Oh, I see, but you used them in your project too, right? Or am I wrong.

**Comment by attila-at-hyper** [comment]
Nope, not used in my project.

**Comment by 3lvis** [comment]
Closing old issues, since they might not be relevant.
